### ISSUE TITLE
Wallet freezes upon syncing

### ISSUE THREAD

**Issue by dburks1** [guapcrypto/Guapcoin#3]
This issue tracker is only for technical issues related to Guapcoin Core.
General Guapcoin questions and/or support requests and are best directed to the [Guapcoin Discord](https://discordapp.com/invite/9nzt37V).

Issue that I am having is when I activate or log in to the PC Wallet, the wallet then syncs up to the block chain and then once completed freezes. I’ve tried deleting the required files in the GUAP folder to reset the wallet to no avail. 
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Log in wallet
2.wait until wallet synchronizes fully
3. Click on anything within the wallet
4. Wallet will not engage/freezes

### Expected behavior
Tell us what should happen
Wallet shouldn’t freeze
### Actual behavior
Tell us what happens instead
Should be able to click and use all features in wallet
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Guapcoin Core are you using?
V2.2.0

List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:
- CPU:Intel(R) i3-8145U @2.10 GHz
- RAM: 8.0 GB
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by jaylamb1** [comment]
> This issue tracker is only for technical issues related to Guapcoin Core.
> General Guapcoin questions and/or support requests and are best directed to the [Guapcoin Discord](https://discordapp.com/invite/9nzt37V).
> 
> Issue that I am having is when I activate or log in to the PC Wallet, the wallet then syncs up to the block chain and then once completed freezes. I’ve tried deleting the required files in the GUAP folder to reset the wallet to no avail.
> 
> ### Can you reliably reproduce the issue?
> Yes
> 
> #### If so, please list the steps to reproduce below:
> 1. Log in wallet
>    2.wait until wallet synchronizes fully
> 2. Click on anything within the wallet
> 3. Wallet will not engage/freezes
> 
> ### Expected behavior
> Tell us what should happen
> Wallet shouldn’t freeze
> 
> ### Actual behavior
> Tell us what happens instead
> Should be able to click and use all features in wallet
> 
> ### Screenshots.
> If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
> 
> ### What version of Guapcoin Core are you using?
> V2.2.0
> 
> List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
> 
> ### Machine specs:
> * OS:
> * CPU:Intel(R) i3-8145U @2.10 GHz
> * RAM: 8.0 GB
> * Disk size:
> * Disk Type (HD/SDD):
> 
> ### Any extra information that might be useful in the debugging process.
> This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

Do you have any masternode controllers setup on your wallet? If so how many? I've seen the QT wallet on Windows slow down when there are around 20 masternode controllers active. Can you post your debug.log file.

**Comment by dburks1** [comment]
How are you Jason!
I’m assuming that we do have controllers on the wallet we have 19 master nodes. Currently nothing is responding. When I log in the app the screen fades white and stall out. I’m not sure how to get the debug.log file, I tried to go to the file and click on the notepad but I doesn’t respond.

**Comment by dburks1** [comment]
Hello, 
       Following back up with the below. Would like to get this resolved soon please. Thanks in advance.

**Comment by Shinoa-Fores** [comment]
> How are you Jason! I’m assuming that we do have controllers on the wallet we have 19 master nodes. Currently nothing is responding. When I log in the app the screen fades white and stall out. I’m not sure how to get the debug.log file, I tried to go to the file and click on the notepad but I doesn’t respond.
> […](#)
> On Sep 29, 2020, at 10:11 PM, jaylamb1 ***@***.***> wrote: ﻿ This issue tracker is only for technical issues related to Guapcoin Core. General Guapcoin questions and/or support requests and are best directed to the Guapcoin Discord. Issue that I am having is when I activate or log in to the PC Wallet, the wallet then syncs up to the block chain and then once completed freezes. I’ve tried deleting the required files in the GUAP folder to reset the wallet to no avail. Can you reliably reproduce the issue? Yes If so, please list the steps to reproduce below: Log in wallet 2.wait until wallet synchronizes fully Click on anything within the wallet Wallet will not engage/freezes Expected behavior Tell us what should happen Wallet shouldn’t freeze Actual behavior Tell us what happens instead Should be able to click and use all features in wallet Screenshots. If the issue is related to the GUI, screenshots can be added to this issue via drag & drop. What version of Guapcoin Core are you using? V2.2.0 List the version number/commit ID, and if it is an official binary, self compiled or a distribution package. Machine specs: OS: CPU:Intel(R) i3-8145U @2.10 GHz RAM: 8.0 GB Disk size: Disk Type (HD/SDD): Any extra information that might be useful in the debugging process. This is normally the contents of a debug.log, db.log or config.log file. Raw text or a link to a pastebin type site are preferred. Do you have any masternode controllers setup on your wallet? If so how many? I've seen the QT wallet on Windows slow down when there are around 20 masternode controllers active. Can you post your debug.log file. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

19 master nodes that are little more than docker node sybils.

**Comment by guapcrypto** [comment]
This issue should be closed based on the 2.3.1 updates. We are unable to reproduce the issue.
