### ISSUE TITLE
Clicking MasterNode FAQ crashes app requiring restart - Linux Wallet 

### ISSUE THREAD

**Issue by jrwill80** [guapcrypto/Guapcoin#5]
After launching the Linux or WIndows Guap Wallet, the UI crashes after clicking the FAQs "What is a Masternode?" or "What is a controller?" 

### Describe the issue
 The UI completely closes and the Linux terminal displays the following error - Segmentation fault (core dumped)
The WIndows version of the app also crashes in a similar fashion 
#### If so, please list the steps to reproduce below:
1. Launch a terminal by pressing ctrl+alt+t
2. cd to the folder containing the quapcoin-qt file
3. enter ./guapcoin-qt
4. press enter to launch the Guapcoin wallet 
5. The GuapCoin UI is displayed.  - Select the [Master Nodes] option from the left navigation menu
6. Click - What is a MasterNode 
7. The Guap Wallet]application unexpectedly terminates. The terminal displays the following error - Segmentation fault (core dumped)
8. Repeat steps  1-5
9. Click - What is a controller
10. The Guap Wallet\application unexpectedly terminates. The terminal displays the following error - Segmentation fault (core dumped) 

Windows 10 - 
1. Install the Guap app using the executable extracted from the zip file
2. Launch the Guap application
3.The GuapCoin UI is displayed.  - Select the [Master Nodes] option from the left navigation menu
4. Click - What is a MasterNode 
6. The Guap Wallet\application unexpectedly terminates. 
7. Repeat steps  2-3
8. Click - What is a controller
9. The Guap Wallet\application unexpectedly terminates. 
### Expected behavior
The expected behavior should result in the Wallet UI displaying a window which provides a detailed answer to the FAQ

### Actual behavior
The Guap Wallet unexpectedly terminates. The terminal displays the following error - Segmentation fault (core dumped) 

### Screenshots.
![masternode-issue](https://user-images.githubusercontent.com/76441780/102797878-48211500-437e-11eb-9e26-0d99e5eedb6c.png)
![segment-fault](https://user-images.githubusercontent.com/76441780/102797941-60912f80-437e-11eb-8b1f-3fe8422065c8.jpeg)

### What version of Guapcoin Core are you using? 2.3.0-Linux
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: Using Ubuntu 18.04.5 LTS 64-BIT
- CPU: Intel i7 Q740 1.73GHZ x 8
- RAM: 7.7GB
- Disk size: 340GB
- Disk Type: SDD

### Any extra information that might be useful in the debugging process.
contents from debug.log 

2020-12-21 16:16:48 connect() to [2600:8805:170a:6700::5cee]:9633 failed: Network is unreachable (101)

**Comment by guapcrypto** [comment]
Issue has been resolved in v2.3.1
