### ISSUE TITLE
TOR functionality visible but not implemented

### ISSUE THREAD

**Issue by jrwill80** [guapcrypto/Guapcoin#6]
#### If so, please list the steps to reproduce below:
1. Install the app
2. Click the TOR icon
3. Observe the end-result

### Expected behavior
Clicking the Tor button on the Guap application should enable private tor network to send Guap coins
### Actual behavior
The TOR button appears to be for aesthetics only 
### Screenshots.
N/A
### What version of Guap coin Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
v 2.30
### Machine specs:
- OS: WIndows 64 
- CPU: I7 Q 740
- RAM: 8gb
- Disk size: 300GB
- Disk Type SDD

### Machine specs:
- OS: Ubuntu 18.04
- CPU: I7 Q 740
- RAM: 8gb
- Disk size: 300GB
- Disk Type SDD

### Machine specs:
- OS: Android 10 Samsung Tablet 
- CPU: ARM 
- RAM: 8gb
- Disk size: 80GB
- Disk Type SDD

**Comment by guapcrypto** [comment]
The tor function is not a built in feature, there are a few extra steps that need to be carried out to send over Tor. Instructions will be listed on the dev gitlab.
